// <auto-generated />
namespace PSIRSCashBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditCashbookDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditCashbookDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201802231852367_EditCashbookDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
